### ISSUE TITLE
Help needed adding VueJS to this App.

### ISSUE THREAD

**Issue by mal90** [mal90/adApp#1]
Currently this adApp application uses AngularJS as the front-end technology . I want to migrate to VueJS . If anyone wants to contribute , holler at me :)

**Comment by viettrung9012** [comment]
@mal90 I'd like to help but I'm pretty new to VueJS and it has been long time since I used AngularJS

**Comment by mal90** [comment]
@viettrung9012 I am also pretty new to VueJS :) . But this project doesn't require a lot of Knowledge . Okay as the first step , can you create a separate branch from master and try add VueJS dependencies to the index.html . Create a PR once you done and i will check and merge :)

**Comment by viettrung9012** [comment]
@mal90 I created PR #2 
Took me awhile to use my local mongo in server.js

**Comment by meetzaveri** [comment]
I can help, I have worked on vue.js and its good to implement. But first you will have to change file structures according to vue.js components

**Comment by mal90** [comment]
@meetzaveri can you propose the vue file structure ?

**Comment by meetzaveri** [comment]
@mal90 First of all remove all angular files including folder of controllers and services. Instead in src folder use components that means component-based structure. Also add routing where single file i.e. main file would render another files on lazy loading means when necessary. Name root file as app.vue which include components and has routes to them.

**Comment by meetzaveri** [comment]
For help you can check file structures mentioned in my vuejs projects .

**Comment by mal90** [comment]
@meetzaveri Thank you for the tips .

**Comment by mal90** [comment]
@meetzaveri As per your suggestion , i converted the application to vue component based architecture .The code is pushed to the branch [vue-migration branch](https://github.com/mal90/adApp/tree/add-vue-migration). It is been successful so far . But i have issue when i tried to access the express backend api running in localhost.

I am currently using vue webpack-simple template . So when i run the application it runs on `localhost:8080 port` . Where as the express server runs in `localhost:3000` port . When i try to send a `$http.get` method to access backend `/api/products` end i am getting the a 404 error saying localhost:8080/api/products not found . 

My question is how to do i access the `localhost:3000/api/products` in the backend from the vuejs application which runs in `localhost:8080` ?

**Comment by meetzaveri** [comment]
Hey @mal90 that's great that you have migrated to vue.js structure. Let me check issue and it will take time.

**Comment by mal90** [comment]
@meetzaveri thank you ! I have created a separate issue in a different thread #3 .
