### ISSUE TITLE
Help needed accessing express-backend from vuejs front-end

### ISSUE THREAD

**Issue by mal90** [mal90/adApp#3]
So this is a very simple application i started implementing to learn vuejs , node , express and webpack .
Code contains in this branch [adApp vue](https://github.com/mal90/adApp/tree/add-vue-migration) (NOT in master!)

Current problem i have is aceessing an api end in express backend `/api/products/`
[link to server.js file](https://github.com/mal90/adApp/blob/add-vue-migration/server.js)

```
.... //more code here 

MongoClient.connect(URL, (err, database) => {
  if (err) 
    return console.log(err);
  db = database;
  app.listen(3000, () => {
    console.log('listening on 3000');
  })
})

app.get('/api/products', (req, res) => {
    db.collection('products').find().toArray(function(err, results) {
    console.log(results)
    res.setHeader('Content-Type', 'application/json');
    res.send(JSON.stringify(results));
    })
})
```

I have used vue webpack-simple template and it uses 8080 port to run the application . However my server runs in 3000 port . I am trying access `/api/products/` using a simple get method as follows
[link to Product.vue file](https://github.com/mal90/adApp/blob/add-vue-migration/src/components/Products.vue)

```
export default {
  name: 'Products',
  methods: {
        get: function() {
            // GET request
            this.$http({
                url: '/api/products',
                method: 'GET'
            }).then(function(response) {
                console.log('ok');
            }, function(response) {
                console.log('failed');
            });
        }
    }
}
```
I get the 404 error like this

![image](https://user-images.githubusercontent.com/8871285/31707815-f4828e14-b3b2-11e7-9b6f-05b71e78ba08.png)

I understand this error . Since it tries to access the backend api end using localhost:8080 port therefore it throws a 404. How i can solve this issue ?

I've found few suggestion to use webpack dev server proxy . So i did as follows in the webpack.config.js

```
devServer: {
    historyApiFallback: true,
    noInfo: true,
     proxy: {
       "/api/*": "http://localhost:3000/api/"
     }
  },
```
But still i get the same result . If anyone can give me a solution or point me in the right direction is highly appreciated .

**Comment by viettrung9012** [comment]
I think you can get it work with
```
proxy: {
  "/api" : "http://localhost:3000"
}
```

**Comment by viettrung9012** [comment]
Created a PR for the fix.

However, I think the proper way for this would be setup a 'dev' script in package.json to do the following step:
1. Use webpack to build static files in `/dist`
2. Run server.js to serve static files in `/dist`

Setup a watcher to re-run when files changed would be useful too

**Comment by saurabhnemade** [comment]
```
    proxy: {
		"/api/": {
			target: "http://localhost:8090/",
			secure: false
		}
    }
```

This works.

**Comment by mal90** [comment]
closing this issue as @viettrung9012 PR was accepted and merged . Will work on the improvements based on @viettrung9012 comments :)
